### PR TITLE
Accessibility efforts

### PR DESCRIPTION
**Pull request by danielfilho**
## TODO
- [x] Skip to content
- [ ] Make timestamp links more semantic
- [ ] Add `aria` roles
### Skip to content

access

I think @reinaldoferraz would be proud of this.

---

### CODE REVIEW

**Comment by reinaldoferraz** [comment]
Absolutely! If you need some help just let me know.

**Comment by bpassos** [comment]
I made a start with the addition of ARIA roles! \o/

**Comment by reinaldoferraz** [comment]
Consider the "skip do content" jumping directly to the player. Accesskey could provide direct access to the player,but it would be necessary to notify the user. You can add the info directly on the link. Something like "Ir para o conteúdo - accesskey 1". Nice documentation about this is available at http://webaim.org/techniques/keyboard/accesskey

**Comment by obetomuniz** [comment]
Subtitles can help deaf people.

**Comment by cirocosta** [comment]
Nicely done! What do you think about "measuring" it and then having metric to enforce it in future PRs? IMO that's a must (could be stated in `CONTRIBUTING` - even though people generally don't look at it :cry: )  

There's that classic developer tools extension for chrome (https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb?utm_source=chrome-app-launcher-info-dialog), addyosmani's cli (https://github.com/addyosmani/a11y) tool (i think this is the one that suits better for what i'm proposing) and also Khan academy's (http://khan.github.io/tota11y/) tota11y, which focuses on the development processes.

**Comment by cirocosta** [comment]
`a11y` nesse PR até então: https://gist.github.com/cirocosta/1f0c45d701f395a3bc66

**Comment by bpassos** [comment]
Good point, done!

**Comment by fititnt** [comment]
Use accesskeys for accessibility on 2015? Why?

**Comment by reinaldoferraz** [comment]
I have some arguments about the use of at least one accesskey for accessibility:

- Skip to navigation does not work in the same way in all browsers. There is an old bug in Webkit  browsers (since 2009) that does not allow the keyboard navigation via anchor.
- Some HTML5 semantic elements (such as header, main, section, etc) still have lack of implementation in some screen readers. It is still necessary to use ARIA to skip some website areas
- You can use a H1-H6 structure instead of accesskey, but using accesskey to access the main content (specially a podcast) help people who cannot navigate by headings achieve the content via keyboard , like people with motor disabilities.
- Keyboard navigation is helpful and important for mobile. Some assistive tecnology (like VoiceOver, for IOs) allows user to navigate via swipe gesture (finger movement right to left focus the next link/semantic element and finger movement left to right focus the previous one)
- It is a single attribute in the page. Easy to implement.
- Is still part of HTML5 spec http://www.w3.org/TR/html5/editing.html#the-accesskey-attribute

**Comment by danielfilho** [comment]
@bpassos can you merge with staging and reopen this poiting to staging, not master, please? :)

**Pull request closed without merging**
