### PR TITLE
Post: correct img responsive the .mosaic class

### PR DESCRIPTION
**Pull request by dionealves**
There is a bug that image where it stretches rather than the proportion
mander
bug in mosaic class

*Pardon if any problems happen, but here it worked*

### CODE REVIEW

**Comment by bpassos** [comment]
Hello @dionealves, thanks for submitting this PR. We actually removed the images from the episodes as the hero image is the same image. What needs to be done is go through all the old episodes (or at least the past 10) and remove that image.

Is this something you are able to do?

Cheers!

**Comment by bpassos** [comment]
This is what the new episode page looks like.

To achieve this in the previous episode pages we need to remove the second image as mentioned above and add the right classes to the timeline markdown.

screen shot 2015-09-24 at 16 49 39

**Comment by dionealves** [comment]
I remove it manually in each episode, and in that file I sent, add these two parameters:
```CSS
/* --- removing the image --- */
div.row p img {
     display: none
}
/* --- editing classes --- */
div.row the p {
     background: # EACD15;
     color: # 897700;
     padding: 3px 15px;
}
```
Which of the two forms would rather be done?

**Comment by bpassos** [comment]
That was fast @dionealves! :+1: 

So, the image tag can actually be removed from the {post}.md file.
With regards to the class added to the episode timeline to get the yellow background around the links only, There is a little trick where we can add it to the markdown it self, so only that element gets the style.

Like this:
[0:01:42](#t=0:01:42){: .timer} [Mais vídeos publicados da BrazilJS](https://www.youtube.com/playlist?list=PLg2lQYZDBwORUpJTu5MxI71iEQIyc_Lno){: .timer-title}<br>

where {.timer} and {.timer-title} are the css classes. You can find the styles given to these classes here: assets/sass/modules/_episode.sass

Because we are using sass, we don't actually need to put semicolons (;) nor curly-braces ({}) to the css. Also, for the colour to be valid, there should be no spaces between the # and the hexdecimal colour value.

I hope this makes sense (Please shout if it doesn't).

It's awesome to have your contribution! :+1: 

Cheers!

**Comment by bpassos** [comment]
@dionealves please push your changes to the staging branch so we can test them in our staging environment before it goes to production.

**Comment by danielfilho** [comment]
changes must be pushed do `staging` branch. please, read the [CONTRIBUTING.md](https://github.com/zofepod/zofe/blob/master/CONTRIBUTING.md) as the pull request suggests, before contributing.

thanks for your help, @dionealves

**Comment by danielfilho** [comment]
let's keep the convo on the new PR that @dionealves will open ;)

**Pull request closed without merging**
