### PR TITLE
Fix the length attribute of enclosure tag - Podcast feed

### PR DESCRIPTION
**Pull request by philss**
It also adds the `audio_file_length` to the source files of posts.

The length attribute is the size in bytes of the audio file.

You can get this value using cURL. Example:

    curl -I -L http://zofe.com.br/episodios/zofe-0-apresentacao

The "Content-Length" header is what we want. If the URL follow
redirects (which is the case of SoundCloud), you may need to take
the last value for the audio file length (which is the bigger number).

This issue is related to #68

### CODE REVIEW

**Comment by philss** [comment]
In case you are wondering, [this](https://gist.github.com/philss/511612d3e68056c0f504) is the script used to fetch file lengths and update the posts.

**Comment by niltoncms** [comment]
Awesome!

**Comment by niltoncms** [comment]
All the podcast feeds that I'm inspecting work right in this way and...  It worked for me too in the app!

Lista de podcast, com o atributo length consertado

**Comment by caiogondim** [comment]
Uploaded the builded site to http://tmp.caiogondim.com
Can we double check if the issue was resolved for you?

**Comment by niltoncms** [comment]
Thanks for the testing area, @caiogondim !

For me worked perfectly.

**Comment by philss** [comment]
@caiogondim @niltoncms Thanks for the testing area.
It's ok for me as well! My Podcast app read the feed without problems. 

:+1:

**Comment by caiogondim** [comment]
Thank you so much for figuring out the problem, guys.
Will wait @danielfilho to merge and deploy.

**Comment by danielfilho** [comment]
I'm at my home town but without a computer to deploy it. 

tomorrow it will be in production. 

thank guys. love you all :)

**Comment by philss** [comment]
@danielfilho \o/

I forgot to mention one thing: every new episode will require the `audio_file_length` attribute to be filled. This can be made as I described in this PR description.

We can create some kind of task to do that automatically if you think it's necessary.
Please let me know if there is something pending to get this merged.

**Comment by danielfilho** [comment]
I already set that on the 21st, @philss. you can check that [here](https://raw.githubusercontent.com/zofepod/zofe/master/_posts/2015-02-23-zofuncional.md).

I just need to take ten minutes to check all changes. today I was a bit in a rush, so I think I can manage the merge tomorrow morning and then, :shipit: :D

thanks again!

**Comment by philss** [comment]
@danielfilho \o/ :smiley:

**Pull request merged**
