### PR TITLE
Fix to mark the topics before of the actual time

### PR DESCRIPTION
**Pull request by MateusZitelli**
Make the progress-traker mark just the topics in the past of the
actual player time.

### CODE REVIEW

**Comment by rafaelrinaldi** [comment]
Great stuff @MateusZitelli! :rocket:

**Comment by rafaelrinaldi** [comment]
@MateusZitelli The tests pass but we've lost the highlighting when you go from a breakpoint to another :disappointed: Can you please install it locally, manually test it and then send a new PR?

I'm reverting this so users don't have a broke experience online.

Thank you.

**Comment by danielfilho** [comment]
working now.
that was an error generated by me.
there was no `bower install` on our build process. :)

thanks for contributing, @MateusZitelli

**Comment by MateusZitelli** [comment]
Thank you guys, I expect that it helps.

**Pull request merged**
