### PR TITLE
Staging

### LINKED ISSUE #100: Layout fixes
PDF with some erros i have found http://cl.ly/3T3h2v0r1221

### LINKED ISSUE #110: Fix about page
About page is a little messy. Need some attention.

http://zofe.com.br/sobre/

### PR DESCRIPTION
**Pull request by bpassos**
This pull request fixes #100 and also fix #110

### CODE REVIEW

**Comment by danielfilho** [comment]
@bpassos can we have a padding on the timestamp? feels narrow to have the BG without much room :)

**Comment by bpassos** [comment]
@danielfilho bummer, I added styles to _post.sass but forgot to register the file on main.sass, which means you didnt see any changes I added to the episode page.

Sorry about that!

Fixed and pushed!

**Comment by bpassos** [comment]
It should look like this now:

screen shot 2015-09-06 at 11 30 18

**Comment by cirocosta** [comment]
:+1:

**Pull request merged**
