### PR TITLE
ZOFE 2.0

### PR DESCRIPTION
**Pull request by danielfilho**
This PR stands for the major upgarde on ZOFE

- [ ] Project
  - [ ] Update `README.md` (@danielfilho)
  - [ ] Create a `CONTRIBUTING.md` file
  - [x] Create project config files (jshint, esformatter, editorconfig)
  - [x] Add Travis CI (@danielfilho)
- [x] ZOFE 2.0
  - [x] Refactor CSS from scratch (using SASS)
    - [x] header (@danielfilho)
    - [x] footer (@caiogondim)
    - [x] home-page (@danielfilho)
      - [x] latest episode (@danielfilho)
      - [x] episode list (@danielfilho)
      - [x] pagination (@danielfilho)
    - [x] episode page (@danielfilho)
    - [x] contact page (@caiogondim)
  - [x] Add Grunt to the project (@almirfilho + @danielfilho)
  - [x] Update podcast's hosts (names, pictures, contact) (@almirfilho)
  - [x] Organize touch icons (@almirfilho)
- [ ] ZOFE Trampos
  - [ ] Apply ZOFE SASS

Layouts, created by @bpassos: [https://cloudup.com/cjEHeLbQbMJ](https://cloudup.com/cjEHeLbQbMJ)

### CODE REVIEW

**Comment by danielfilho** [comment]
involving @caiogondim on this :)

**Comment by danielfilho** [comment]
@caiogondim suggested to start using [Skeleton](http://getskeleton.com/) as our main grid system.

:+1:

**Comment by danielfilho** [comment]
@bpassos love you too bro.
this wasn't supposed to happen without you, your love and your skills.
this is slightly different from the original design, but we were really looking forward for a release.
will make it better through time, ok?

THANK YOU SO MUCH, dear friend :clap:

**Comment by bpassos** [comment]
@danielfilho good work buddy! I would love to contribute going forward. I think the responsive version needs some love! <3

**Comment by cirocosta** [comment]
:+1: :+1: :clap: :clap:

**Comment by reidark** [comment]
@danielfilho About the grid system, we can give a chance to [Semantic.gs](http://semantic.gs/)? His code is based on LESS, but we can easily transform this to SASS (syntax).

Just an opinion :D

**Comment by danielfilho** [comment]
we're using skeleton and it's being simple & great.
we should focus on other stuff right now and keep those kind of small decisions for later.

let's save bikeshedding for later :dancer:

**Pull request merged**
